server:
  port: 8088
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&autoReconnect=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&tinyInt1isBit=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 12345678

  output:
    ansi:
      enabled: ALWAYS
logging:
  config: classpath:logback-spring.xml
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.daimt.home.study.batis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # https://blog.csdn.net/qq_39809458/article/details/121793630 myBatis日志输出讲解
#    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: org.daimt.home.study.batis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不进行@TableLogic注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


sms:
  user: daimt